# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/monsud/Scrivania/ASCON-hw/ASCON-hw.srcs/sources_1/bd/design_ascon/ip/design_ascon_processing_system7_0_4/design_ascon_processing_system7_0_4.xci
# IP: The module: 'design_ascon_processing_system7_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/monsud/Scrivania/ASCON-hw/ASCON-hw.gen/sources_1/bd/design_ascon/ip/design_ascon_processing_system7_0_4/design_ascon_processing_system7_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ascon_processing_system7_0_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/monsud/Scrivania/ASCON-hw/ASCON-hw.srcs/sources_1/bd/design_ascon/ip/design_ascon_processing_system7_0_4/design_ascon_processing_system7_0_4.xci
# IP: The module: 'design_ascon_processing_system7_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/monsud/Scrivania/ASCON-hw/ASCON-hw.gen/sources_1/bd/design_ascon/ip/design_ascon_processing_system7_0_4/design_ascon_processing_system7_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ascon_processing_system7_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
